/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./src/components/ui/filters/my-vue-project/node_modules/@vue/cli-plugin-router/generator/template/src/views/AboutView.vue')['default']
    AdminDashboard: typeof import('./src/components/layout/AdminDashboard.vue')['default']
    AdminNavbar: typeof import('./src/components/ui/headers/AdminNavbar.vue')['default']
    AdminSidebar: typeof import('./src/components/ui/sidebars/AdminSidebar.vue')['default']
    ApexDonutChart: typeof import('./src/components/ui/charts/ApexDonutChart.vue')['default']
    App: typeof import('./src/components/ui/filters/my-vue-project/node_modules/@vue/cli-plugin-router/generator/template/src/App.vue')['default']
    AppointmentTable: typeof import('./src/components/ui/tables/AppointmentTable.vue')['default']
    BasicTable: typeof import('./src/components/ui/tables/BasicTable.vue')['default']
    CheckButton: typeof import('./src/components/ui/Buttons/CheckButton.vue')['default']
    ContentCard: typeof import('./src/components/ui/cards/ContentCard.vue')['default']
    ContentTable: typeof import('./src/components/ui/tables/ContentTable.vue')['default']
    EducationalTile: typeof import('./src/components/ui/tiles/EducationalTile.vue')['default']
    FeesTile: typeof import('./src/components/ui/tiles/FeesTile.vue')['default']
    Filter: typeof import('./src/components/ui/filters/Filter.vue')['default']
    HelloWorld: typeof import('./src/components/ui/filters/my-vue-project/node_modules/@vue/cli-service/generator/template/src/components/HelloWorld.vue')['default']
    HomeView: typeof import('./src/components/ui/filters/my-vue-project/node_modules/@vue/cli-plugin-router/generator/template/src/views/HomeView.vue')['default']
    InfoCard: typeof import('./src/components/ui/cards/InfoCard.vue')['default']
    InstockFilter: typeof import('./src/components/ui/filters/InstockFilter.vue')['default']
    InventoryModal: typeof import('./src/components/ui/modals/InventoryModal.vue')['default']
    Manufacturer: typeof import('./src/components/ui/filters/Manufacturer.vue')['default']
    ManufacturerFilter: typeof import('./src/components/ui/filters/ManufacturerFilter.vue')['default']
    MedInventoryTable: typeof import('./src/components/ui/tables/MedInventoryTable.vue')['default']
    PatientModal: typeof import('./src/components/ui/modals/PatientModal.vue')['default']
    PatientTable: typeof import('./src/components/ui/tables/PatientTable.vue')['default']
    PrimaryButton: typeof import('./src/components/ui/Buttons/PrimaryButton.vue')['default']
    ProductFilter: typeof import('./src/components/ui/filters/ProductFilter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryButton: typeof import('./src/components/ui/Buttons/SecondaryButton.vue')['default']
    SelectFilter: typeof import('./src/components/ui/filters/Filtermenu/SelectFilter.vue')['default']
    ShareContent: typeof import('./src/components/ui/modals/ShareContent.vue')['default']
    StaffModal: typeof import('./src/components/ui/modals/StaffModal.vue')['default']
    StaffTable: typeof import('./src/components/ui/tables/StaffTable.vue')['default']
  }
}
