/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminDashboard: typeof import('./src/components/layout/AdminDashboard.vue')['default']
    AdminNavbar: typeof import('./src/components/ui/headers/AdminNavbar.vue')['default']
    AdminSidebar: typeof import('./src/components/ui/sidebars/AdminSidebar.vue')['default']
    ApexDonutChart: typeof import('./src/components/ui/charts/ApexDonutChart.vue')['default']
    AppointmentTable: typeof import('./src/components/ui/tables/AppointmentTable.vue')['default']
    BasicTable: typeof import('./src/components/ui/tables/BasicTable.vue')['default']
    ContentCard: typeof import('./src/components/ui/cards/ContentCard.vue')['default']
    EducationalTile: typeof import('./src/components/ui/tiles/EducationalTile.vue')['default']
    FeesTile: typeof import('./src/components/ui/tiles/FeesTile.vue')['default']
    Filter: typeof import('./src/components/ui/filters/Filter.vue')['default']
    InfoCard: typeof import('./src/components/ui/cards/InfoCard.vue')['default']
    InstockFilter: typeof import('./src/components/ui/filters/InstockFilter.vue')['default']
    InventoryModal: typeof import('./src/components/ui/modals/InventoryModal.vue')['default']
    MedInventoryTable: typeof import('./src/components/ui/tables/MedInventoryTable.vue')['default']
    PatientModal: typeof import('./src/components/ui/modals/PatientModal.vue')['default']
    PatientTable: typeof import('./src/components/ui/tables/PatientTable.vue')['default']
    PrimaryButton: typeof import('./src/components/ui/Buttons/PrimaryButton.vue')['default']
    ProductFilter: typeof import('./src/components/ui/filters/ProductFilter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryButton: typeof import('./src/components/ui/Buttons/SecondaryButton.vue')['default']
    StaffModal: typeof import('./src/components/ui/modals/StaffModal.vue')['default']
    StaffTable: typeof import('./src/components/ui/tables/StaffTable.vue')['default']
  }
}
